name: MyWarp
version: '2.0.1 (+Damage-feature by main())'
author: spathizilla
authors: 
  - flames
  - tkelly
softdepend:
  - Permissions
  - GroupManager
  - PermissionsEx
  - Help
main: me.taylorkelly.mywarp.MyWarp
commands:
  warp:
    description: All of the MyWarp commands
    usage: /<command> help - Displays the help for MyWarp